KwotaSlownie/Controllers/AmountController.cs
using KwotaSlownie.Models;
using KwotaSlownie.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KwotaSlownie.Controllers
{
    public class AmountController : Controller
    {
        public IActionResult Index(AmountModel amountFromView)
        {
            return View(amountFromView);
        }

        [HttpPost]
        public IActionResult AmountInWords(AmountModel amountFromView)
        {
            if (amountFromView.Amount.Contains(".") || !amountFromView.Amount.Contains(","))
            {
                amountFromView.Amount = "Wpisz poprawne dane!";
                return RedirectToAction("Index", amountFromView);
            }

            var amountInWords = AmountToWords.ToWords(amountFromView.Amount);
            var newAmount = new AmountModel { Amount = amountFromView.Amount, AmountInWords = amountInWords, IsNBPCurrency = amountFromView.IsNBPCurrency };

            return RedirectToAction("Index",newAmount);
        }
    }
}
 

KwotaSlownie/Controllers/CurrencyController.cs
using KwotaSlownie.Models;
using KwotaSlownie.Services;
using KwotaSlownie.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KwotaSlownie.Controllers
{
    public class CurrencyController : Controller
    {
        public async Task<IActionResult> Index()
        {
            //download date and currency from last month 
            var currencyList = new List<CurrencyModel>();
            GetCurrency get = new GetCurrency();

            currencyList = await get.ParseRSS();
            var amountViewModel = new CurrencyAmountViewmodel();
            amountViewModel.Amounts = currencyList;

            return View(amountViewModel);
        }
        [HttpPost]
        public IActionResult CalculatedCurrency(CurrencyAmountViewmodel model)
        {
            var amountChoosed= model.ChoosedCurrency / 10000;
            model.ChoosedCurrency = amountChoosed;

            if (model.UserAmount == 0)
            {
                return RedirectToAction("Index");
            }

            return View(model);
        }
    }
}

KwotaSlownie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>kwota słownie</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Amount" asp-action="Index">Kwota słownie</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Amount" asp-action="Index">Słownie</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Currency" asp-action="Index">Przeliczenie z EURO</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - KwotaSlownie - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>